In [4]:
import flordb as flor
import pandas as pd
runs = flor.get_runs()      # neither worked. or flor.get_runs()

AttributeError: module 'flordb' has no attribute 'get_runs'

In [5]:
runs = flor.load_runs()

AttributeError: module 'flordb' has no attribute 'load_runs'

In [7]:
df= flor.dataframe()
df

,projid,tstamp,filename,run_name,dataset_root,robot_port,teleop_port,repo_id,num_episodes,episode_time_s,...,gpu_end/name,gpu_end/util_pct,gpu_end/mem_util_pct,gpu_end/mem_used_mb,gpu_end/mem_total_mb,gpu_end/mem_free_mb,gpu_end/temp_c,gpu_end/power_w,gpu_end/sm_clock_mhz,gpu_end/mem_clock_mhz
0,lerobotwithflor,2026-02-25 13:40:39,record_with_flor.py,so101_3cam_20260225_134040,C:\Users\Erick Duarte\git\lerobotwithflor\data...,COM6,COM5,BarbaricErick/so101_3cam_demo,10,180,...,None,None,None,None,None,None,None,None,None,None
1,lerobotwithflor,2026-02-27 14:53:54,train_with_flor.py,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,lerobotwithflor,2026-02-27 15:15:10,train_with_flor.py,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,lerobotwithflor,2026-02-27 15:17:10,train_with_flor.py,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,lerobotwithflor,2026-02-27 15:18:17,train_with_flor.py,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
5,lerobotwithflor,2026-02-27 15:19:16,train_with_flor.py,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
6,lerobotwithflor,2026-02-27 15:21:05,train_with_flor.py,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
7,lerobotwithflor,2026-02-27 15:24:54,train_with_flor.py,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
8,lerobotwithflor,2026-02-27 15:26:13,train_with_flor.py,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
9,lerobotwithflor,2026-02-27 15:31:08,train_with_flor.py,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
10,lerobotwithflor,2026-02-27 15:54:22,train_with_flor.py,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
11,lerobotwithflor,2026-02-27 16:09:01,train_with_flor.py,None,None,None,None,None,None,None,...,NVIDIA GeForce RTX 3070,1,4,1232.8,8192.0,6959.2,44,20.4,210,405

In [8]:
df.columns.tolist()

['projid',
 'tstamp',
 'filename',
 'run_name',
 'dataset_root',
 'robot_port',
 'teleop_port',
 'repo_id',
 'num_episodes',
 'episode_time_s',
 'reset_time_s',
 'push_to_hub',
 'task',
 'event',
 'started_utc',
 'finished_utc',
 'return_code',
 'elapsed_s',
 'success',
 'output_contains_timeout',
 'output_contains_read_failed',
 'cfg/policy_type',
 'cfg/dataset_repo_id',
 'cfg/output_dir',
 'cfg/log_every',
 'cfg/sys_every',
 'cfg/stdout_every',
 'cfg/run_tag',
 'cfg/seed',
 'cfg/extra',
 'sys/os',
 'sys/machine',
 'sys/python',
 'sys/executable',
 'sys/torch_version',
 'sys/cuda_available',
 'cfg_policy_type',
 'cfg_dataset_repo_id',
 'cfg_output_dir',
 'cfg_log_every',
 'cfg_sys_every',
 'cfg_stdout_every',
 'cfg_run_tag',
 'cfg_seed',
 'cfg_extra',
 'sys/cuda_version',
 'sys/gpu_name',
 'git/commit',
 'git/dirty',
 'sys/psutil_available',
 'sys/pynvml_available',
 'train/cmd',
 'train/run_start_ts',
 'train/run_end_ts',
 'train/run_duration_s',
 'train/return_code',
 'gpu/name',
 'gpu/util_pct',
 'gpu/mem_util_pct',
 'gpu/mem_used_mb',
 'gpu/mem_total_mb',
 'gpu/mem_free_mb',
 'gpu/temp_c',
 'gpu/power_w',
 'gpu/sm_clock_mhz',
 'gpu/mem_clock_mhz',
 'gpu_end/name',
 'gpu_end/util_pct',
 'gpu_end/mem_util_pct',
 'gpu_end/mem_used_mb',
 'gpu_end/mem_total_mb',
 'gpu_end/mem_free_mb',
 'gpu_end/temp_c',
 'gpu_end/power_w',
 'gpu_end/sm_clock_mhz',
 'gpu_end/mem_clock_mhz']

In [9]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 12 entries, 0 to 11
Data columns (total 76 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   projid                       12 non-null     object
 1   tstamp                       12 non-null     datetime64[ns]
 2   filename                     12 non-null     object
 3   run_name                     1 non-null      object
 4   dataset_root                 1 non-null      object
 5   robot_port                   1 non-null      object
 6   teleop_port                  1 non-null      object
 7   repo_id                      1 non-null      object
 8   num_episodes                 1 non-null      object
 9   episode_time_s               1 non-null      object
 10  reset_time_s                 1 non-null      object
 11  push_to_hub                  1 non-null      object
 12  task                         1 non-null      object
 13  event                        1 non-null      object
 14  started_utc                  1 non-null      object
 15  finished_utc                 1 non-null      object
 16  return_code                  1 non-null      object
 17  elapsed_s                    1 non-null      object
 18  success                      1 non-null      object
 19  output_contains_timeout      1 non-null      object
 20  output_contains_read_failed  1 non-null      object
 21  cfg/policy_type              1 non-null      object
 22  cfg/dataset_repo_id          1 non-null      object
 23  cfg/output_dir               1 non-null      object
 24  cfg/log_every                1 non-null      object
 25  cfg/sys_every                1 non-null      object
 26  cfg/stdout_every             1 non-null      object
 27  cfg/run_tag                  1 non-null      object
 28  cfg/seed                     1 non-null      object
 29  cfg/extra                    1 non-null      object
 30  sys/os                       11 non-null     object
 31  sys/machine                  11 non-null     object
 32  sys/python                   11 non-null     object
 33  sys/executable               11 non-null     object
 34  sys/torch_version            11 non-null     object
 35  sys/cuda_available           11 non-null     object
 36  cfg_policy_type              10 non-null     object
 37  cfg_dataset_repo_id          10 non-null     object
 38  cfg_output_dir               10 non-null     object
 39  cfg_log_every                10 non-null     object
 40  cfg_sys_every                10 non-null     object
 41  cfg_stdout_every             10 non-null     object
 42  cfg_run_tag                  10 non-null     object
 43  cfg_seed                     10 non-null     object
 44  cfg_extra                    10 non-null     object
 45  sys/cuda_version             10 non-null     object
 46  sys/gpu_name                 10 non-null     object
 47  git/commit                   10 non-null     object
 48  git/dirty                    10 non-null     object
 49  sys/psutil_available         10 non-null     object
 50  sys/pynvml_available         10 non-null     object
 51  train/cmd                    10 non-null     object
 52  train/run_start_ts           10 non-null     object
 53  train/run_end_ts             10 non-null     object
 54  train/run_duration_s         10 non-null     object
 55  train/return_code            10 non-null     object
 56  gpu/name                     1 non-null      object
 57  gpu/util_pct                 1 non-null      object
 58  gpu/mem_util_pct             1 non-null      object
 59  gpu/mem_used_mb              1 non-null      object
 60  gpu/mem_total_mb             1 non-null      object
 61  gpu/mem_free_mb              1 non-null      object
 62  gpu/temp_c                   1 non-null      object
 63  gpu/power_w                  1 non-null      object
 64  gpu/sm_clock_mhz             1 non-null      object
 65  gpu/mem_clock_mhz            1 non-null      object
 66  gpu_end/name                 1 non-null      object
 67  gpu_end/util_pct             1 non-null      object
 68  gpu_end/mem_util_pct         1 non-null      object
 69  gpu_end/mem_used_mb          1 non-null      object
 70  gpu_end/mem_total_mb         1 non-null      object
 71  gpu_end/mem_free_mb          1 non-null      object
 72  gpu_end/temp_c               1 non-null      object
 73  gpu_end/power_w              1 non-null      object
 74  gpu_end/sm_clock_mhz         1 non-null      object
 75  gpu_end/mem_clock_mhz        1 non-null      object
dtypes: datetime64[ns](1), object(75)
memory usage: 7.2+ KB

In [10]:
train_df = df[df["filename"] == "train_with_flor.py"]
train_df

,projid,tstamp,filename,run_name,dataset_root,robot_port,teleop_port,repo_id,num_episodes,episode_time_s,...,gpu_end/name,gpu_end/util_pct,gpu_end/mem_util_pct,gpu_end/mem_used_mb,gpu_end/mem_total_mb,gpu_end/mem_free_mb,gpu_end/temp_c,gpu_end/power_w,gpu_end/sm_clock_mhz,gpu_end/mem_clock_mhz
1,lerobotwithflor,2026-02-27 14:53:54,train_with_flor.py,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
2,lerobotwithflor,2026-02-27 15:15:10,train_with_flor.py,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
3,lerobotwithflor,2026-02-27 15:17:10,train_with_flor.py,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
4,lerobotwithflor,2026-02-27 15:18:17,train_with_flor.py,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
5,lerobotwithflor,2026-02-27 15:19:16,train_with_flor.py,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
6,lerobotwithflor,2026-02-27 15:21:05,train_with_flor.py,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
7,lerobotwithflor,2026-02-27 15:24:54,train_with_flor.py,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
8,lerobotwithflor,2026-02-27 15:26:13,train_with_flor.py,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
9,lerobotwithflor,2026-02-27 15:31:08,train_with_flor.py,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
10,lerobotwithflor,2026-02-27 15:54:22,train_with_flor.py,None,None,None,None,None,None,None,...,None,None,None,None,None,None,None,None,None,None
11,lerobotwithflor,2026-02-27 16:09:01,train_with_flor.py,None,None,None,None,None,None,None,...,NVIDIA GeForce RTX 3070,1,4,1232.8,8192.0,6959.2,44,20.4,210,405

In [11]:
import pandas as pd

runs = df[df["train/cmd"].notna()].copy()   # only rows that actually ran lerobot-train
runs = runs.sort_values("tstamp").reset_index(drop=True)

# convert key numeric columns from object -> numeric
num_cols = [
    "train/run_duration_s",
    "train/return_code",
    "cfg_log_every",
    "cfg_sys_every",
    "cfg_seed",
]
for c in num_cols:
    if c in runs.columns:
        runs[c] = pd.to_numeric(runs[c], errors="coerce")

runs[[
    "tstamp",
    "filename",
    "cfg_output_dir",
    "git/commit",
    "git/dirty",
    "train/return_code",
    "train/run_duration_s",
]]

,tstamp,filename,cfg_output_dir,git/commit,git/dirty,train/return_code,train/run_duration_s
0,2026-02-27 15:15:10,train_with_flor.py,outputs/smoke_smolvla,f9f424e5e22d458648a346c78dd3e2e99ca88871,True,2,31.750419
1,2026-02-27 15:17:10,train_with_flor.py,outputs/smoke_smolvla,9bd6444f098ea8b1dd6e060ccc8424ef0137b5b7,False,1,11.352166
2,2026-02-27 15:18:17,train_with_flor.py,outputs/smoke_smolvla,e9976863980283b1bfdcdb2e6d59b0a79e0873b2,False,1,11.370687
3,2026-02-27 15:19:16,train_with_flor.py,outputs/smoke_smolvla,4eaf92f3984d21e0d1ed3a632da5f68d879c484f,False,1,53.343012
4,2026-02-27 15:21:05,train_with_flor.py,outputs/smoke_smolvla,04929c7661f18d22e39dafcbc547843894383bc9,False,1,77.142292
5,2026-02-27 15:24:54,train_with_flor.py,outputs/smoke_smolvla,6a04fb0fc556d9b374b7b7d2aff0a1b2a538427b,False,1,11.276880
6,2026-02-27 15:26:13,train_with_flor.py,outputs/smoke_smolvla_run2,5f944f47c3aa23d680171470fe80ae5a2e1faa2e,False,0,76.255974
7,2026-02-27 15:31:08,train_with_flor.py,outputs/smoke_smolvla_run3,c5e9c61598c253ced8aa36b467699bd1c19c4167,False,0,77.805079
8,2026-02-27 15:54:22,train_with_flor.py,outputs/smoke_smolvla_run4,a0af70fbfbb07e59583f4606a0a23e2b2c2b413c,True,0,80.220668
9,2026-02-27 16:09:01,train_with_flor.py,outputs/smoke_smolvla_run5,7c27148bd56de512600c12ea2e524c5e4d4fd7e7,True,0,78.837976

In [12]:
import flordb as flor
[x for x in dir(flor) if "event" in x.lower() or "record" in x.lower() or "log" in x.lower()]

['log']

In [16]:
from huggingface_hub import scan_cache_dir

cache_info = scan_cache_dir()

for repo in cache_info.repos:
    if "so101_3cam_merged" in repo.repo_id:
        print(repo.repo_id)
        print("Location:", repo.repo_path)