In [6]:
import flordb as flor
import pandas as pd

# This is the "long" table of log records (one row per log event)
records = flor.dataframe("event")  # try a likely key you logged
records.tail(20)

            projid              tstamp             filename            event
0  lerobotwithflor 2026-02-25 13:40:39  record_with_flor.py  recording_start
1  lerobotwithflor 2026-02-25 13:40:39  record_with_flor.py    recording_end

In [8]:
import flordb as flor

df = flor.dataframe()    
df

,projid,tstamp,filename,run_name,dataset_root,robot_port,teleop_port,repo_id,num_episodes,episode_time_s,...,push_to_hub,task,event,started_utc,finished_utc,return_code,elapsed_s,success,output_contains_timeout,output_contains_read_failed
0,lerobotwithflor,2026-02-25 13:40:39,record_with_flor.py,so101_3cam_20260225_134040,C:\Users\Erick Duarte\git\lerobotwithflor\data...,COM6,COM5,BarbaricErick/so101_3cam_demo,10,180,...,False,Pick up the red cylinder and place it centered...,recording_start,2026-02-25T20:40:40Z,2026-02-25T20:48:52Z,0,492.4615879058838,True,False,False

In [10]:
import flordb as flor
flor.dataframe("event", "success", "elapsed_s")

,projid,tstamp,filename,event,success,elapsed_s
0,lerobotwithflor,2026-02-25 13:40:39,record_with_flor.py,recording_start,True,492.4615879058838
1,lerobotwithflor,2026-02-25 13:40:39,record_with_flor.py,recording_end,True,492.4615879058838